### ISSUE TITLE
Highlighting does not work properly

### ISSUE THREAD

**Issue by iampeter** [go-lang-plugin-org/go-lang-idea-plugin#2784]
- Plugin version (or commit hash): 0.12.1724
- IntelliJ IDEA 2016.2.4
- Build #IU-162.2032.8, built on September 9, 2016
- JRE: 1.8.0_112-release-b343 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

After upgrading to 2016.3 EAP (163.4830.24), Intellij IDEA reported the plugin is not compatible with this version, so I downgraded to IntelliJ IDEA 2016.2.4.

Then the plugin stopped highlighting properly, also linking to references does not work. Cleared cache, reinstalled plugin etc multiple times.

An example of highlighing problem attached - only basic keywords are recognized.

![high](https://cloud.githubusercontent.com/assets/713801/18833021/e78864ee-83ee-11e6-9518-0fd6cfafe51d.png)

**Comment by dlsniper** [comment]
Hi,

Is the plugin enabled (I know, it's silly but I have to double check)? And if so, is the Color Scheme that you used the one that's currently in use (see ` Editor | Colors & Fonts | Go `.
If not, I have a couple of other places to check but I'd rather remove the obvious ones first.
Thank you.

**Comment by iampeter** [comment]
@dlsniper yes, it is enables, the scheme is Monokai Sublime Text 3.

Frankly just realized code completion does not work as well. The feature I see working are go-related configurations, like compilation / running.

what I just saw in logs:
```
2016-09-26 14:20:52,065 [ 222848]  ERROR - aemon.impl.PassExecutorService - Could not initialize class com.intellij.codeInsight.completion.CompletionUtil 
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.codeInsight.completion.CompletionUtil
	at org.intellij.plugins.intelliLang.inject.InjectorUtils.findCommentInjection(InjectorUtils.java:253)
	at org.intellij.plugins.intelliLang.inject.AbstractLanguageInjectionSupport.findCommentInjection(AbstractLanguageInjectionSupport.java:63)
	at org.intellij.plugins.intelliLang.inject.CommentLanguageInjector.getLanguagesToInject(CommentLanguageInjector.java:66)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:458)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:313)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:145)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:213)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInjectableElements(InjectedLanguageManagerImpl.java:217)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.collectLineMarkersForInjected(LineMarkersPass.java:212)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:112)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2016-09-26 14:20:52,066 [ 222849]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 2016.2.4  Build #IU-162.2032.8 
2016-09-26 14:20:52,066 [ 222849]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_112-release 
2016-09-26 14:20:52,066 [ 222849]  ERROR - aemon.impl.PassExecutorService - VM: OpenJDK 64-Bit Server VM 
2016-09-26 14:20:52,066 [ 222849]  ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 
2016-09-26 14:20:52,066 [ 222849]  ERROR - aemon.impl.PassExecutorService - OS: Linux 
2016-09-26 14:20:52,066 [ 222849]  ERROR - aemon.impl.PassExecutorService - Last Action: ShowLog 
```

**Comment by dlsniper** [comment]
I think something happened with the IntelliJ installation. What's version of the Go plugin do you have now?

**Comment by iampeter** [comment]
plugin version: 0.12.1724

I just re-installed IDEA 2016.2.4 again, and still the same

**Comment by dlsniper** [comment]
There's a hidden folder called ` ~/.IntelliJIdea2016.2/ `, can you please stop your IDE, temporarily move that to a different folder and then start the IDE again? It will reset the IDE settings and everything and you'll have to reinstall the Go plugin.
Please let me know if that works.

**Comment by iampeter** [comment]
OK so what worked for me right now, is reinstalling to a clean directory. Just overwritting must have left from files from 2016.3 EAP. I kept my settings (`~/.IntelliJIdea2016.2/`).

Thank you for your assistance @dlsniper

**Comment by dlsniper** [comment]
Oh, ok, that makes sense. Happy I could help. And yes, for now the plugin does not support the latest 2016.3 EAP. I'll close this and please feel free to reopen / open a new one if you need further help.
