### ISSUE TITLE
Java exception in "Select GOROOT folder" dialog

### ISSUE THREAD

**Issue by dmytro-vovk** [go-lang-plugin-org/go-lang-idea-plugin#859]
After upgrade of go from 1.3.1 to 1.3.3 tried to add new SDK to IDEA by opening Project Structure dialog and clicking Project Settings > Project > New... > Go SDK. Dialog window "Select GOROOT Folder" opens but clicking OK button generates the following exception:

```
com.intellij.execution.configurations.GeneralCommandLine.withWorkDirectory(Ljava/lang/String;)Lcom/intellij/execution/configurations/GeneralCommandLine;: com.intellij.execution.configurations.GeneralCommandLine.withWorkDirectory(Ljava/lang/String;)Lcom/intellij/execution/configurations/GeneralCommandLine;
java.lang.NoSuchMethodError: com.intellij.execution.configurations.GeneralCommandLine.withWorkDirectory(Ljava/lang/String;)Lcom/intellij/execution/configurations/GeneralCommandLine;
    at ro.redeul.google.go.runner.GoRunProfileState.startProcess(GoRunProfileState.java:82)
    at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:74)
    at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:38)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:48)
    at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:208)
    at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:180)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:246)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:259)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:41)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:66)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:32)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:54)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:32)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:138)
    at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:394)
    at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:61)
    at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:375)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

The same exception happens when I try to run my current configuration.
