### ISSUE TITLE
Can't build in Idea 11 build 111.167

### ISSUE THREAD

**Issue by idaunis** [go-lang-plugin-org/go-lang-idea-plugin#70]
I'm getting this annoying error:

8:33:19 PM NoSuchMethodError: Error during dispatching of java.awt.event.MouseEvent[MOUSE_PRESSED,(50,115),absolute(433,253),button=1,modifiers=Button1,extModifiers=Button1,clickCount=1] on dialog10: com.intellij.execution.RunConfigurationExtension.writeSettings(Lcom/intellij/execution/configurations/RunConfigurationBase;Lorg/jdom/Element;)V
