### ISSUE TITLE
v1.0.0: Type checking is not performed

### ISSUE THREAD

**Issue by horkhe** [go-lang-plugin-org/go-lang-idea-plugin#1016]
Type errors are not reported neither for assignments nor for functions calls

``` Go

func Foo(a int) {
}

func Bar() {
    Foo("") // Should be error: "cannot use "" (type string) as type int in argument to Foo"
    var str string = 1 // Should be error: "cannot use 1 (type int) as type string in assignment"
    str = 2 // Should be error: "cannot use 2 (type int) as type string in assignment"
    str = Foo(1) // Should be error: "cannot use Foo(1) (type int) as type string in assignment"
    return str
}
```

**Comment by Kane-Sendgrid** [comment]
still doesn't work in 0.9.264, what's the plan on fixing this?

**Comment by ignatov** [comment]
still doesn't have a million in my pocket,  what's the plan on fixing this?

**Comment by juliandroid** [comment]
Unfortunately it seems there is no type compatibility checking. See the following example:

```
package typerr

import "fmt"

type Coffee interface {
	make() int
}

type Arabica struct {
}

type Robusta struct {
}

func (c Arabica) make() int {
	return 1
}

func (c *Robusta) make() int {
	return 2
}

func test() {
	var c1 Coffee
	var c2 Coffee
	var c3 Coffee

	c1 = Arabica{}
	c2 = Robusta{} // Should be an error. *Robusta was meant
	c3 = "text"    // Should be an error.

	fmt.Printf("%v %v", c1.make(), c2.make(), c3.make())
}

```

```
$ go build typetest.go 
# command-line-arguments
./typetest.go:29: cannot use Robusta literal (type Robusta) as type Coffie in assignment:
	Robusta does not implement Coffie (make method has pointer receiver)
./typetest.go:30: cannot use "wtf?!" (type string) as type Coffie in assignment:
	string does not implement Coffie (missing make method)

```
In editors like Vim and Atom it seems the error checking is done by directly using the go compiler to do the full syntax check, so it works correctly every time.

**Comment by dlsniper** [comment]
@juliandroid type inference is not something that can be easily done and the plugin doesn't rely on tools like the go compiler to do the checks. There are many differences between a glorified text editor with plugins and a proper IDE which makes this not feasible. Also, as soon as the IDE will get type inference things like autocompletion can become a lot better than in other editors.
This issue is currently open so it will be fixed at some point, meanwhile thank you for the sample, it will be useful to verify the functionality once implemented.

**Comment by juliandroid** [comment]
Sure, but I thought having go compiler doing the hard part at the beginning, until the real type inference parser is done would be a good idea.

**Comment by dlsniper** [comment]
@juliandroid I know that in theory it sounds nice and easy but unfortunately it's not like that (and believe me I've got bitten a few times assuming this). We'll get there some day but meanwhile if you want to give this a Go then please go ahead, we'd be happy to have more contributors to the plugin.
