### ISSUE TITLE
[1.0] Support for AppEngine Go SDK

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1278]
AppEngine SDK is not supported right now and it should be.

**Comment by dlsniper** [comment]
Fixed.

**Comment by jimbojetlag** [comment]
Why is this closed?

- There is no way to create an app engine project.
- There is no way to launch an app engine go app.

Also, things have slightly changed since gae 1.9.18, and the old goapp path does not work anymore, intead `google-cloud-sdk/bin/goapp` must be used.

**Comment by dlsniper** [comment]
@jimbojetlag it's closed because there's support for creating the SDK inside the IDE so all the other code level functions work.

Please detail the change you are referring about the change in the path as I can't find anything in the release notes such a change https://code.google.com/p/googleappengine/wiki/SdkForGoReleaseNotes

How did you installed the GAE SDK for Go? Personally, I've downloaded the SDK from https://cloud.google.com/appengine/downloads, unzipped into /usr/local/go_appengine and that's it.

As for running the AppEngine app from the IDE, I'll discuss this with @zolotov to see if it's something we should do or not since AppEngine apps are in fact running a continuous server and that server can reload the app. If he thinks we should reopen this with that point, I'll do so.

**Comment by zolotov** [comment]
@dlsniper well, at least we can do deploying. Not sure about launching, maybe 1.0.maybe? :)

@jimbojetlag personally I don't use GAE, so it's easy to miss some slightly changes in it. Meanwhile the plugin is open sourced and ```Also, things have slightly changed since gae 1.9.18, and the old goapp path does not work anymore, instead google-cloud-sdk/bin/goapp must be used.``` looks like great opportunity to contribute in it.

**Comment by dlsniper** [comment]
@zolotov yes, deploying could look like something we could do. I can work on it for 1.0 or next.
However, I've seen that there's an [AppEngine](https://plugins.jetbrains.com/plugin/4254?pr=idea) plugin with IDEA Ultimate so, should we integrate with that or do we want to rollout something custom for Go only?

**Comment by zolotov** [comment]
> However, I've seen that there's an AppEngine plugin with IDEA Ultimate so, should we integrate with that or do we want to rollout something custom for Go only?

Definitely not custom. Will try to integrate with existing solution, maybe it will be available for Ultimate/PhpStorm/PyCharmPro only.

**Comment by dlsniper** [comment]
Ok, it makes sense for me. I'll open up the issue for deployment. Thank you.

**Comment by dlsniper** [comment]
@jimbojetlag I've just tried the AppEngine 1.9.18 and I can't see any changes. I'm not an active user of AppEngine so as @zolotov mentioned, any help with this is greatly appreciated. Thank you.

**Comment by jimbojetlag** [comment]
@dlsniper sorry, I had the impression that this issues also covers launching a gae app.

I know gae runs its own continuous server, and doing its own 'go fmt', it can interfere with open files (as it happened with the old plugin). But having the output of the server inside IDE, and specially being able to click on error lines to to go the right file and line, is very valuable.

The issue with gae 1.9.18 is only relevant when launching the app inside the IDE.

- Should the SDK dir point to `google-cloud-sdk`, or `google-cloud-sdk/platform/google_appengine`?
- After creating a go project, the IDE is not aware of go packages inside the project root. Do I have to add the project directory path to GOPATH manually for every project?
- Why does a go gae project need an `out/` directory? It is not required, and it interferes with the external build process.

**Comment by dlsniper** [comment]
@jimbojetlag no worries. Thank you for your feedback, it's really appreciated.

I can see the point of having the GAE server launched from the IDE, but I'll have to get some help from Alexander or Sergey in order to see how we can do that and not interfere with what IDEA expects to be build / run process as I don't have the required experience with this (or with the builtin support for AppEngine). Can you please open a different ticket just for this part and detail the use case so that we can have a clear target and others can follow the progress in this one?

As for your other points:

> Should the SDK dir point to google-cloud-sdk, or google-cloud-sdk/platform/google_appengine?

Can you please detail how you installed the SDK? For linux, at least, I've detailed the process above and things are fairly straight forward. Unfortunately I don't have a Mac or Windows so I can't help that much.

> After creating a go project, the IDE is not aware of go packages inside the project root. Do I have to add the project directory path to GOPATH manually for every project?

This one depends on your use case. In my case, I have one GOPATH for all projects in my system so I've added a single entry to the ```Settings | Languages & Frameworks | Go``` under ```Global Libraries``` panel. If you want to have things shared across projects, that's the way to do it. If you have particular GOPATHs for paricular projects, then I'd recommend to add it to ```Project Libraries``` panel.

> Why does a go gae project need an out/ directory? It is not required, and it interferes with the external build process.

I think that's just a quirk (might be the default in IDEA as far as I've seen). Things are still a work in project in regards to building projects and they require work and this is one of them.

**Comment by jimbojetlag** [comment]
Sure, here is the issue: #1387.

> Can you please detail how you installed the SDK? For linux, at least, I've detailed the process above and things are fairly straight forward. Unfortunately I don't have a Mac or Windows so I can't help that much.

I simply extract it to the default directory, which is in `~`. By `google-cloud-sdk/` I meant the installation directory.

> This one depends on your use case. In my case, I have one GOPATH for all projects 

I think it makes sense to have the project root directory in the path for that project. Go App Engine dev server does this. Otherwise, every time the project directory is changed, we need to update the absolute path to the project dir.

**Comment by juanibiapina** [comment]
By reading the discussion on this issue, I understand goappengine is working well on the latest 1.0 release candidate. Is this the case?

For me is doesn't work at all. I have compilation problems in IntelliJ, problems building the project (NullPointerException) and other issues.

On 0.9 it works for a few minutes, then it breaks and we have to invalidate caches in order to continue.

Is anyone else trying to use this in a serious appengine project? What would you recommend me do?

**Comment by dlsniper** [comment]
@juanibiapina in the latest 1.0 release appengine should work ok (minus the things discussed, ofc). If it's not the case, please create different issues containing details about the problems you are experiencing in order for us to be able to look into them and fix them.

From what I understand, you have problems with running the project from inside IDEA. This, as you can read above, is not a functionality we currently support unfortunately. You can track the status of it here: #1387 Ofc, if you'd like to see it done faster, any help would be greatly appreciated.

Thank you.
